// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ServiceLayer.Models;

public partial class Task
{
    public Guid Id { get; set; }

    public string Name { get; set; }

    public DateTime Created { get; set; }

    public DateTime? Updated { get; set; }

    public Guid ListId { get; set; }

    public int? CategoryId { get; set; }
}